### ISSUE TITLE
 detcted user name and passworld of sql in Dnspy OUR..........

### ISSUE THREAD

**Issue by erfan132** [XeCrash/NETLock#2]
detcted user name and passworld of sql in Dnspy our Wireshok(use vmare to open app and then listen it)

i think you can use olther way to give sql information 
tnx for amazing Project

**Comment by XeCrash** [comment]
This is something that is better for you the end user to do. I can suggest that you obfuscate the program and encrypt the strings as a method of protecting your connection string. You can't just hide it from outside viewers unless you obfuscate it or store an encrypted version of the connection string on a website and decrypt it within the application which is another good way to do it.

**Comment by erfan132** [comment]
hello
i have request beside show username
in admin panel show ip of users
our HWID

On Nov 30, 2017 10:55, "XeCrash" <notifications@github.com> wrote:

Closed #2 <https://github.com/XeCrash/NETLock/issues/2>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/XeCrash/NETLock/issues/2#event-1365062195>, or mute the
thread
